#debug: true

server:
  port: 21010
  tomcat.uri-encoding: UTF-8
  server-header: text/plain;charset=UTF-8
  servlet:
    context-path: /
    session.timeout: 900 #session timeout in seconds
spring:
  messages.encoding: UTF-8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  session.store-type: redis
  datasource:
    druid:
      url: jdbc:mysql://118.31.14.156:20003/mro?useUnicode=true&amp;characterEncoding=UTF8
      username: cm
      password: cm123!@#
      driver-class-name: com.mysql.jdbc.Driver
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
  jpa:
      database: MYSQL
      show-sql: true
      hibernate.ddl-auto: update
      hibernate.use-new-id-generator-mappings: true
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      open-in-view: true
  redis:
    database: 0
#    host: 127.0.0.1
    host: 10.154.96.70
    port: 6379
    password: Passw0rd
#    host: 118.31.14.156
#    port: 26379
    jedis:
      pool:
        max-idle: 8
        max-wait: -1
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 100MB
      enabled: true
      max-request-size: 100MB




#esb/odata
zconnection:
  type: odata
  odataIp: http://10.154.96.65
  odataPort: 8000
  odataUser: cg_fangwei
  odataPasswd: siemens
  odataClient: 103
  esbIp: http://10.154.97.1:8010/