server:
  port: 21010
  tomcat.uri-encoding: UTF-8
  server-header: text/plain;charset=UTF-8

  servlet:
    context-path: /
    session.timeout: 900 #session timeout in seconds
spring:
  messages.encoding: UTF-8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  session.store-type: redis
  redis:
    database: 0
    host: 10.154.70.121
    port: 6379
    password: Passw0rd

    jedis:
      pool:
        max-idle: 8
        max-wait: -1
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 100MB
      enabled: true
      max-request-size: 100MB

#esb/odata
zconnection:
  type: odata
  odataIp: http://10.154.2.41
  odataPort: 8000
  odataUser: zn_odata
  odataPasswd: zn_odata
  odataClient: 300
  esbIp: https://mobileesb.zjenergy.com.cn