package com.magustek.com.htxtpc.util.test;

import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.math.BigDecimal;

@Getter
@Setter
public class TestContractHeaderSet implements Serializable {

    private String Htnum;//合同管理编号
    private String Htsno;//合同流水号
    private String Htbnr;//合同编号
    private String Xdfms;//相对方名称
    private String Zzxdf;//相对方编码
    private String Fhtbh;//关联父合同编号
    private String Fhtnm;//关联框架协议合同名称
    private String Stonr;//工作状态
    private String Sptxt;//审批状态
    private String Istat;//系统状态
    private String Istxt;//系统状态描述
    private String Htart;//业务类
    private String Nflag;//新记录标记
    private String Flchk;//法律审核标记
    private String Loevm;//删除
    private BigDecimal Dmbtr;//总金额(元)
    private BigDecimal Afbtr;//变更后总金额
    private BigDecimal Zbbtr;//质保金
    private BigDecimal Yfktr;//预付款金额
    private BigDecimal Ysktr;//预收款金额
    private BigDecimal Sfbtr;//累计实付金额
    private BigDecimal Lsbtr;//累计实收金额
    private String Waers;//货币
    private String Ktext;//货币名称
    private String Zszlx;//收支类型
    private String Sztxt;//收支类型描述
    private String Zdjfs;//定价方式
    private String Djtxt;//定价方式描述
    private String Cbrid;//用户名
    private String Zzcbr;//承办人
    private String Jbrid;//经办人账号
    private String Jbren;//业务经办人
    private String Jbgsb;//经办部门编号
    private String Zlydb;//是否有履约担保
    private String Dbtyp;//担保类型
    private BigDecimal Lybzj;//履约保证金
    private String Dbdat;//担保截至日期
    private String Esdat;//开始日期
    private String Efdat;//结束日期
    private String Qddat;//签订日期
    private String Zgddd;//签订地点
    private String Spdat;//审批通过日期
    private String Zlxfs;//手机号码
    private BigDecimal Bgbil;//变更金额比例
    private BigDecimal Zbgbl;//总变更金额比例
    private String Zzspd;//审批到
    private String Zspxl;//审批效率
    private String Fxtxt;//风险等级
    private String Zfxdj;//风险预警
    private String Sfdsh;//是否上董事会
    private String Sfgdh;//是否上股东会
    private String Zjlbg;//总经理办公室会
    private String Sfckn;//是否超框架协议-内容
    private String Sfckj;//是否超框架协议-金额
    private String Lrnys;//是否列入当年预算
    private String Zgljy;//是否关联交易
    private String Sfztb;//生产综合类物资招标会
    private String Sfgcl;//工程类会议
    private String Sfzjh;//中介服务领导小组会
    private String Sfqth;//其他会议
    private String Hyyj;//会议意见
    private String Gbtyp;//关闭类型
    private String Gbtxt;//关闭类型描述
    private String Gbdat;//关闭日期
    private String Xstyp;//选商方式
    private String Xstxt;//选商方式描述
    private String Xytyp;//寻源方式
    private String Zyysx;//用印顺序
    private String Sxtxt;//用印顺序描述
    private String Zyylx;//用印类型
    private String Yytxt;//用印类型描述
    private String Zyyrq;//用印日期
    private String Zhtwb;//用印份数
    private String Zhtfj;//合同附件用印份数
    private String Yyrid;//印章管理员账号
    private String Htyyr;//印章管理员
    private String Yyrbm;//印章管理员部门
    private String Patyp;//付款构成类型
    private String Sqtyp;//授权类型
    private String Sqtxt;//授权类型描述
    private String Zsqbh;//授权编号
    private String Bzsqh;//转授权编号
    private String Bgtyp;//合同变更类型
    private String Bgrsn;//变更原因
    private String Bgtxt;//合同变更内容
    private BigDecimal Bfbtr;//变更前总金额
    private String Bgbnr;//变更申请单号
    private String Zsxtj;//生效条件
    private String Budat;//凭证中的过帐日期
    private String Zfkyt;//付款用途
    private String Gjahr;//会计年度
    private String Accou;//相对方收款银行帐户
    private String Banka;//相对方收款银行名称
    private String Sknam;//收款人名称
    private BigDecimal Sdbtr;//本次付款前累计抵扣预付款金额(付款)
    private BigDecimal Qczlj;//累计担保处置金额
    private BigDecimal Qyflj;//本次付款前累计应付金额
    private BigDecimal Qyslj;//本次收款前累计应收金额
    private BigDecimal Qfplj;//本次付款前累计取得发票金额
    private BigDecimal Qyfkl;//本次付款前累计预付款金额
    private BigDecimal Qyskl;//本次收款前累计预收款金额
    private BigDecimal Qylkl;//本次付款前累计预留款
    private BigDecimal Qylkf;//本次付款前累计预留款返还
    private BigDecimal Qylkl_s;//本次收款前累计预留款金额
    private BigDecimal Qylkf_s;//本次收款前累计预留款收回
    private BigDecimal Ljkpj;//本次收款前累计开票金额
    private BigDecimal Lybzj_ljf;//累计返回履约保证金
    private BigDecimal Ljbzj;//累计抵扣履约保证金
    private BigDecimal Ljzbj;//累计预留质保金(付款)
    private BigDecimal Ljzbj_s;//累计预留质保金(收款)
    private BigDecimal Ljzbf;//累计返还质保金(付款)
    private BigDecimal Ljzbf_s;//累计收回质保金(收款)
    private BigDecimal Ljbzj_f;//累计预留保证金(付款)
    private BigDecimal Ljbzj_s;//累计预留保证金(收款)
    private BigDecimal Ljbzf_f;//累计返还保证金(付款)
    private BigDecimal Ljbzf_s;//累计收回保证金(收款)
    private BigDecimal Otbtr;//其他累计抵扣金额(付款)
    private BigDecimal Otbtr_s;//其他累计抵扣金额(收款)
    private BigDecimal Sdbtr_s;//本次收款前累计抵扣预收款金额(收款)
    private BigDecimal Sqbtr;//本次付款前累计申请付款金额
    private BigDecimal Sqbtr_s;//本次收款前累计申请收款金额
    private BigDecimal Qkklj;//本次付款前累计扣款金额
    private BigDecimal Qkklj_s;//本次收款前累计扣款金额
    private String Prefh;//待发货
    private String Predh;//待到货确认
    private String Preys;//待验收
    private String Prejs;//待结算
    private String Predj;//待发票登记
    private String Presq;//待付款
    private String Bstat;//业务状态
    private String Bstxt;//业务状态描述
    private String Fhnot;//发货说明
    private String Dhnot;//到货说明
    private String Ysnot;//验收说明
    private String Jsnot;//结算说明
    private BigDecimal Qyjkl;//本次付款前累计支付预结款(元)
    private BigDecimal Jdbtr;//本次付款前累计抵扣预结款(元)
    private BigDecimal Qyjkl_s;//本次收款前累计收取预结款(元)
    private BigDecimal Jdbtr_s;//本次收款前累计抵扣预结款(元)
    private BigDecimal Zyflj;//累计应付余额
    private BigDecimal Pjmar;//评价分数
    private String Qwfkr;//期望付款日期
    private String Sjfkr;//实际付款日期
    private String Bczfz;//本次支付状态
    private String Ohtnu;//前业务合同管理编号
    private String Jbrbm;//经办人部门
    private String Ahtnu;//后业务合同管理编号
    private BigDecimal Bcsqf;//本次申请付款金额
    private BigDecimal Bcsqs;//本次申请收款金额
    private BigDecimal Bcsqj;//本次申请结算金额
    private BigDecimal Wybtr;//本次其他扣款金额
    private String Ibukrs;//需求单位代码
    private String Uname;//用户姓名
    private String Zwanr;//内部发货单号
    private String Ibutxt;//需求单位公司名称
    private String Eindt;//交货日期
    private String Zjflg;//增减标识
    private String Phone;//经办人手机号
    private String Crname;//创建者
    private String Chname;//最后更改者
    private String Chdate;//对象最后一次更改日期
    private String Flgfk;//标识：集采或自采
    private BigDecimal Fhbtr;//本次发货金额
    private BigDecimal Dhbtr;//本次到货金额
    private String Msgtype;//消息类型
    private String Msgtext;//消息文本
    private String Aflag;//动作标识
    private String Loginname;//登录用户名
    private String Usersource;//用户来源
    private String Orgcode;//组织机构编号
    private String Deptcode;//部门编号
    private String Actorcode;//职位编号

}
